### ISSUE TITLE
install.py fails because PyQT5 can't be installed with PIP.

### ISSUE THREAD

**Issue by dB-SPL** [W5DMH/CommStatXR#1]
I was unable install using the included install.py file because PyQT5 couldn't be installed with PIP. This occurred on both a Raspberry Pi 4 and Raspberry Pi 400 running Buster.  The error message and a work-around is included below:

```
user@host:~/commstatx $ python3 install.py
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyqt5
  Downloading https://files.pythonhosted.org/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 116kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-q36nlo3t/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q36nlo3t/pyqt5/
Traceback (most recent call last):
  File "install.py", line 20, in <module>
    install(firstmodule)
  File "install.py", line 13, in install
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'pyqt5']' returned non-zero exit status 1.

```

I was able to manually install PyQT5 with `sudo apt install python3-pyqt5` then the rest of the dependencies with `python3 -m pip install feedparser file-read-backwards folium`.

On first run, the settings window launched as expected.  After entering the required info, the script didn't appear to use the log location I entered, but failed with:

```
user@host:~/commstatx $ python3 commstatx.py 
qt5ct: using qt5ct plugin
...
qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "commstatx.py", line 795, in <module>
    ui.setupUi(MainWindow)
  File "commstatx.py", line 263, in setupUi
    self.directed()
  File "commstatx.py", line 524, in directed
    with open(path) as f, open('output.txt', 'w') as fout:
FileNotFoundError: [Errno 2] No such file or directory: '/home/DIRECTED.TXT'
``

The settings were saved, though, because it seemed to work correctly in the following try.

**Comment by W5DMH** [comment]
Looks like you are pathed to python3.7 and the software is designed for python 3.9....The primary reason for Python3.9 is that PyQt5 does not perform well on 3.7 

The last issue with the error when the setup file closes is normal behavior but I will hide it and force a restart in future releases.
